// ng-echo-plex/src/app/app.component.ts
import { Component, ElementRef } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  signal = 'app';
  logEvent(event) {
    console.log(event);
  }

  setVal() {
    this.signal = 'Hello';
  }

  setInterval(echoCmp: any) {
    echoCmp.setDelayTime(200);
  }
}

<echo-plex
  #echoCmp
  [signal]="signal"
  (echoEmitted)="logEvent($event)"
  >
</echo-plex>

<button (click)="setVal()">Change the Signal</button>
<button (click)="setInterval(echoCmp)">Change the delay Interval</button>

// vue-echo-plex/src/App.vue
<template>
<div>
  <echo-plex :signal="signal" @echoEmitted="logEvent($event)"></echo-plex>
  <button @click="setVal()">Change the Signal</button>
  <button @click="setInterval()">Change the delay Interval</button>
</div>
</template>

<script lang="ts">
import Vue from 'vue';
export default Vue.extend({
  name: 'app',
  data() {
    return {
      signal: 'app'
    }
  },
  methods: {
   setVal: function () {
     this.signal = 'Hello';
    },
    setInterval: function(){
      (this.$el.querySelector('echo-plex') as any).setDelayTime(200);
    },
    logEvent: function(event: any) {
     console.log(event);
    }
  }
});
</script>
