// vue-echo-plex/src/App.vue
<template>
<div>
  <echo-plex :signal="signal" @echoEmitted="logEvent($event)"></echo-plex>
  <button @click="setVal()">Change the Signal</button>
  <button @click="setInterval()">Change the delay Interval</button>
</div>
</template>

<script lang="ts">
import Vue from 'vue';
export default Vue.extend({
  name: 'app',
  data() {
    return {
      signal: 'app'
    }
  },
  methods: {
   setVal: function () {
     this.signal = 'Hello';
    },
    setInterval: function(){
      (this.$el.querySelector('echo-plex') as any).setDelayTime(200);
    },
    logEvent: function(event: any) {
     console.log(event);
    }
  }
});
</script>

// react-echo-plex/src/App.js
import React, { Component } from 'react';
import { wc } from './wc';
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      signal: 'app'
    };
  }
  setVal() {
    this.setState({
      signal: 'Hello'
    });
  }
  logEvent(e) {
    console.log(e);
  }
  render() {
    return (
      <div>
        <echo-plex
          signal={this.state.signal}
          ref={
            wc({
            echoEmitted: e => this.logEvent(e)
          })}
        />
        <button onClick={() => this.setVal()}>Change the Signal</button>
      </div>
    );
  }
}

export default App;
